services:
  - type: web
    name: tgauto-worker
    env: python
    plan: free
    rootDir: worker
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_BASE_URL
        sync: false
      - key: WORKER_TOKEN
        sync: false
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: TG_SESSION
        sync: false
      - key: PORT
        value: 10000
